### ISSUE TITLE
Improve testing config file to be more self-describable

### ISSUE THREAD

**Issue by lvirbalas** [vmware/go-vcloud-director#48]
### Context

Currently it's easy to put incorrect values into the config.yaml file, because it's not clear how the tests work. When you see the config for the first time, you think - will the tests create these resources or is it asking for existing ones?

Another issue is that the user needs to create this file manually, also its name is too generic (config.yaml).

### Requests

To make it easier for the contributors to run tests:

1.) **Rename** the `config.yaml` -> `govcd_test_config.yaml`
2.) **Create a sample file** in the repository (currently, the user needs to create it from scratch).
3.) **Add in-line comments** to the file describing each field that requires an explanation. Luckily, the Yaml parser we use recognises comments.
4.) **Update TESTING.md** accordingly.

### Specific Examples

Below is a list of specific examples, where a reasonable comment would resolve the confusion.

- "user:" - it's not clear whether it's asking for System Administrator, which will create everything else, or an existing Org Administrator.
- "org:", "vdc:", "catalog:" items, "vapp:", "network:", "edgetogateway:" - existing ones or names for the new ones that will get created?
- "externalip:" - an unused, but available external IP, or an IP that the Edge Gateway has (currently, it's the latter). If you make a mistake here, you'll get the following error:
```
"error reconfiguring Edge Gateway: API Error: 400: [ d212c6c4-51b0-496e-b232-0164780300b3 ] External IP 10.150.211.54-10.150.211.54 for NAT should belong to the sub-allocated IP range  of the edge gateway."
```
- "internalip:" - again, not clear for what purpose and whether it's an assigned one or free.

We need a comment above or besides each of the above parameter lines in the config file, explaining how to specify them without guesswork.

**Comment by auppunda** [comment]
@lvirbalas At the moment I think it would be a good idea to skip the edgegateway tests. @dataclouder came up with idea of actually testing edgegateways when we can create vdcs and edgegateways. That way we don't have lasting effects on the users vdc/GW. I will however also update TESTING.md to document this better

**Comment by dataclouder** [comment]
This is an example of how the configuration file with comments will look like.
```yaml
# All items in this file must exist already
# (They will not be removed or left altered)
provider:
    # It's the Org administrator
    user: someuser
    password: somepassword
    # The vCD address, in the format https://vCD_IP/api
    # or https://vCD_host_name/api
    url: https://10.111.1.111/api
vcd:
    # Name of the organization (mandatory)
    org: myorg
    # The virtual data center (mandatory)
    vdc: myvdc
    # An Org catalog, possibly containing at least one item
    catalog:
        name: mycat
        # One item in the catalog. It will be used to compose test vApps
        catalogitem: myitem
        # An optional description for the catalog. Its test will be skipped if omitted.
        # If provided, it must be the current description of the catalog
        description: mycat for loading
        # An optional description for the catalog item
        catalogitemdescription: myitem to create vapps
    # An Org vDC catalog
    network: mynet
    # Storage profiles used in the vDC
    # One or two can be listed
    storageprofile:
        storageprofile1: Development
        storageprofile2: "*"
    # A vApp from the vDC
    vapp: myvapp
    # An edge gateway
    # (see https://pubs.vmware.com/vca/topic/com.vmware.vcloud.api.doc_56/GUID-18B0FB8B-385C-4B6D-982C-4B24D271C646.html)
    edgegateway: myedgegw
    # The IP of the gateway
    externalip: 10.150.10.10
    # The IP of a VM in the vApp provided above
    internalip: 10.0.0.10
```

There are other improvements/additions that could go here. For example, users may set a limit to the resources used by the test, or disallow some types of operations. Future enhancements of the library may also require a different set of credentials. 

Please comment here with all that you think is needed for current and future operations.

**Comment by lvirbalas** [comment]
Looks good!

**Comment by hodgesrm** [comment]
@auppunda I would include edge gateway tests. We can treat the edge gateway as a fixture and just ask users to give the name as a configuration property.  That means to test you'll have to set up a vdc with an edge.  It's easy enough to do.

**Comment by auppunda** [comment]
@hodgesrm alright ok. Then I'll just document the values in the config file better

**Comment by dataclouder** [comment]
In addition to the above example, the configuration file could add a **log** section:
```yaml
log:
    enabled: true
    log_file_name: my-project.log
    log_http_requests: false
    log_http_responses: true
```
